//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.26 at 07:47:22 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "com.github.bukama.ir/01.00", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.github.bukama.ir.jaxb;
